/** @file
  This file contains the Misc version Data (SMBIOS data type 0x94)

  Copyright (c) 1999 - 2016, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php.

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

**/

#include "CommonHeader.h"
#include "MiscSubclassDriver.h"

//
// Static (possibly build generated) Oem data.
//
MISC_SMBIOS_TABLE_DATA(EFI_MISC_OEM_TYPE_0x94, MiscOemType0x94) = {

STRING_TOKEN (STR_MISC_FVI_PLATFORM),
STRING_TOKEN (STR_MISC_IFWI_VERSION_STRING),
STRING_TOKEN (STR_MISC_IFWI_VERSION_VALUE),
STRING_TOKEN (STR_MISC_BIOS_VERSION_STRING),
STRING_TOKEN (STR_MISC_BIOS_VERSION_VALUE),
STRING_TOKEN (STR_MISC_CSE_VERSION_STRING),
STRING_TOKEN (STR_MISC_CSE_VERSION_VALUE),
STRING_TOKEN (STR_MISC_GOP_VERSION_STRING),
STRING_TOKEN (STR_MISC_GOP_VERSION_VALUE),
STRING_TOKEN (STR_MISC_MRC_VERSION_STRING),
STRING_TOKEN (STR_MISC_MRC_VERSION_VALUE),
STRING_TOKEN (STR_MISC_UCODE_STRING),
STRING_TOKEN (STR_MISC_UCODE_VALUE),
STRING_TOKEN (STR_MISC_PUNIT_FW_STRING),
STRING_TOKEN (STR_MISC_PUNIT_FW_VALUE),
STRING_TOKEN (STR_MISC_PMC_FW_STRING),
STRING_TOKEN (STR_MISC_PMC_FW_VALUE),
STRING_TOKEN (STR_MISC_ISH_FW_STRING),
STRING_TOKEN (STR_MISC_ISH_FW_VALUE),
STRING_TOKEN (STR_MISC_SOC_STRING),
STRING_TOKEN (STR_MISC_SOC_VALUE),
STRING_TOKEN (STR_MISC_BOARD_ID_STRING),
STRING_TOKEN (STR_MISC_BOARD_ID_VALUE),
STRING_TOKEN (STR_MISC_FAB_ID_STRING),
STRING_TOKEN (STR_MISC_FAB_ID_VALUE),
STRING_TOKEN (STR_MISC_CPU_FLAVOR_STRING),
STRING_TOKEN (STR_MISC_CPU_FLAVOR_VALUE),
STRING_TOKEN (STR_MISC_PMIC_VERSION_STRING),
STRING_TOKEN (STR_MISC_PMIC_VERSION_VALUE),
STRING_TOKEN (STR_MISC_SECURE_BOOT_STRING),
STRING_TOKEN (STR_MISC_SECURE_BOOT_VALUE),
STRING_TOKEN (STR_MISC_BOOT_MODE_STRING),
STRING_TOKEN (STR_MISC_BOOT_MODE_VALUE),
STRING_TOKEN (STR_MISC_SPEED_STEP_STRING),
STRING_TOKEN (STR_MISC_SPEED_STEP_VALUE),
STRING_TOKEN (STR_MISC_CPU_TURBO_STRING),
STRING_TOKEN (STR_MISC_CPU_TURBO_VALUE),
STRING_TOKEN (STR_MISC_CSTATE_STRING),
STRING_TOKEN (STR_MISC_CSTATE_VALUE),
STRING_TOKEN (STR_MISC_ENHANCED_CSTATE_STRING),
STRING_TOKEN (STR_MISC_ENHANCED_CSTATE_VALUE),
STRING_TOKEN (STR_MISC_PACKAGE_CSTATE_STRING),
STRING_TOKEN (STR_MISC_PACKAGE_CSTATE_VALUE),
STRING_TOKEN (STR_MISC_CORE_CSTATE_STRING),
STRING_TOKEN (STR_MISC_CORE_CSTATE_VALUE),
STRING_TOKEN (STR_MISC_GFX_TURBO_STRING),
STRING_TOKEN (STR_MISC_GFX_TURBO_VALUE),
STRING_TOKEN (STR_MISC_S0IX_STRING),
STRING_TOKEN (STR_MISC_S0IX_VALUE),
STRING_TOKEN (STR_MISC_RC6_STRING),
STRING_TOKEN (STR_MISC_RC6_VALUE),
};

