/** @file

Copyright (c) 2004 - 2007, Intel Corporation
All rights reserved. This program and the accompanying materials
are licensed and made available under the terms and conditions of the BSD License
which accompanies this distribution.  The full text of the license may be found at
http://opensource.org/licenses/bsd-license.php

THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

Module Name:

  TempStringToken.h


**/

//
//  DO NOT EDIT -- auto-generated file
//
//  This file is generated by the string gather utility
//
#ifndef _SETUPBROWSERSTRINGS_STRINGS_DEFINE_H_
#define _SETUPBROWSERSTRINGS_STRINGS_DEFINE_H_

// #define $LANGUAGE_NAME                           0x0000
// #define $PRINTABLE_LANGUAGE_NAME                 0x0001
#define FUNCTION_ONE_STRING                      0x0002
#define FUNCTION_TWO_STRING                      0x0003
#define FUNCTION_NINE_STRING                     0x0004
#define FUNCTION_TEN_STRING                      0x0005
#define ENTER_STRING                             0x0006
#define ENTER_COMMIT_STRING                      0x0007
#define ESCAPE_STRING                            0x0008
#define ADJUST_NUMBER                            0x0009
#define PLUS_STRING                              0x000A
#define MINUS_STRING                             0x000B
#define MOVE_HIGHLIGHT                           0x000C
#define MAKE_SELECTION                           0x000D
#define DEC_NUMERIC_INPUT                        0x000E
#define HEX_NUMERIC_INPUT                        0x000F
#define TOGGLE_CHECK_BOX                         0x0010
#define PROMPT_FOR_PASSWORD                      0x0011
#define PROMPT_FOR_NEW_PASSWORD                  0x0012
#define CONFIRM_PASSWORD                         0x0013
#define CONFIRM_ERROR                            0x0014
#define PASSWORD_INVALID                         0x0015
#define PRESS_ENTER                              0x0016
#define PROMPT_FOR_DATA                          0x0017
#define NV_UPDATE_MESSAGE                        0x0018
#define INPUT_ERROR_MESSAGE                      0x0019
#define EMPTY_STRING                             0x001A
#define ARE_YOU_SURE                             0x001B
#define ARE_YOU_SURE_YES                         0x001C
#define ARE_YOU_SURE_NO                          0x001D
#define MINI_STRING                              0x001E
#define SAVE_FAILED                              0x001F
//#define HOME_PAGE_TITLE                          0x001F // not referenced
//#define HOME_ESCAPE_STRING                       0x0020 // not referenced

#endif
