//
//  DO NOT EDIT -- auto-generated file
//
//  This file is generated by the string gather utility
//
#ifndef _DRIVERSAMPLESTRINGS_STRINGS_DEFINE_H_
#define _DRIVERSAMPLESTRINGS_STRINGS_DEFINE_H_

// #define $LANGUAGE_NAME                           0x0000
// #define $PRINTABLE_LANGUAGE_NAME                 0x0001
#define STR_INV_FORM_SET_TITLE                   0x0002
#define STR_INV_FORM_SET_HELP                    0x0003
#define STR_INV_FORM1_TITLE                      0x0004
#define STR_INV_VERSION_TEXT                     0x0005
#define STR_INV_VERSION_HELP                     0x0006
#define STR_INV_VERSION_TEXT2                    0x0007
#define STR_INV_VERSION_TEXT3                    0x0008
#define STR_INV_VERSION_TEXT4                    0x0009
#define STR_INV_VERSION_TEXT5                    0x000A
#define STR_INV_VERSION_TEXT6                    0x000B
#define STR_INV_VERSION_TEXT7                    0x000C
#define STR_INV_VERSION_TEXT8                    0x000D
#define STR_INV_VERSION_TEXT9                    0x000E
#define STR_INV_VERSION_TEXT10                   0x000F
#define STR_INV_VERSION_TEXT11                   0x0010
#define STR_INV_VERSION_TEXT12                   0x0011
#define STR_INV_EMPTY_STRING                     0x0012
#define STR_FORM_SET_TITLE                       0x0013
#define STR_FORM_SET_TITLE_HELP                  0x0014
#define STR_FORM1_TITLE                          0x0015
#define STR_FORM2_TITLE                          0x0016
#define STR_FORM3_TITLE                          0x0017
#define STR_DYNAMIC_TITLE                        0x0018
#define STR_SUBTITLE_TEXT                        0x0019
#define STR_SUBTITLE_TEXT2                       0x001A
#define STR_CPU_STRING                           0x001B
#define STR_CPU_STRING2                          0x001C
#define STR_ONE_OF_PROMPT                        0x001D
#define STR_ONE_OF_HELP                          0x001E
#define STR_ONE_OF_TEXT1                         0x001F
#define STR_ONE_OF_TEXT2                         0x0020
#define STR_ONE_OF_TEXT3                         0x0021
#define STR_ONE_OF_TEXT4                         0x0022
#define STR_ONE_OF_TEXT5                         0x0023
#define STR_ONE_OF_TEXT6                         0x0024
#define STR_BOOT_ORDER1                          0x0025
#define STR_BOOT_ORDER2                          0x0026
#define STR_CHECK_BOX_PROMPT                     0x0027
#define STR_CHECK_BOX_HELP                       0x0028
#define STR_NUMERIC_STEP_PROMPT                  0x0029
#define STR_NUMERIC_READONLY_PROMPT              0x002A
#define STR_NUMERIC_MANUAL_PROMPT                0x002B
#define STR_TALL_HEX_PROMPT                      0x002C
#define STR_NUMERIC_HELP0                        0x002D
#define STR_NUMERIC_HELP1                        0x002E
#define STR_NUMERIC_HELP2                        0x002F
#define STR_PASSWORD_CALLBACK_PROMPT             0x0030
#define STR_PASSWORD_PROMPT                      0x0031
#define STR_PASSWORD_HELP                        0x0032
#define STR_GOTO_FORM1                           0x0033
#define STR_GOTO_FORM2                           0x0034
#define STR_GOTO_FORM3                           0x0035
#define STR_GOTO_DYNAMIC                         0x0036
#define STR_GOTO_DYNAMIC2                        0x0037
#define STR_ERROR_POPUP                          0x0038
#define STR_MY_STRING_PROMPT                     0x0039
#define STR_MY_STRING_HELP                       0x003A
#define STR_MY_STRING_PROMPT2                    0x003B
#define STR_MY_STRING_HELP2                      0x003C
#define STR_TEXT_TEXT_1                          0x003D
#define STR_TEXT_TEXT_2                          0x003E
#define STR_DATE_PROMPT                          0x003F
#define STR_DATE_MONTH_HELP                      0x0040
#define STR_DATE_DAY_HELP                        0x0041
#define STR_DATE_YEAR_HELP                       0x0042
#define STR_TIME_PROMPT                          0x0043
#define STR_TIME_HOUR_HELP                       0x0044
#define STR_TIME_MINUTE_HELP                     0x0045
#define STR_TIME_SECOND_HELP                     0x0046
#define STR_TEXT_HELP                            0x0047
#define STR_GOTO_HELP                            0x0048
#define STR_TEST_OPCODE                          0x0049
#define STR_TEST_OPCODE2                         0x004A
#define STR_EXIT_TEXT                            0x004B
#define STR_NULL_STRING                          0x004C
#define STR_BOOT_OPTIONS                         0x004D
#define STR_BOOT_OPTION1                         0x004E
#define STR_BOOT_OPTION2                         0x004F
#define STR_BOOT_OPTION3                         0x0050
#define STR_BOOT_OPTION4                         0x0051
#define STR_VAR_NAME                             0x0052
//#define STR_CHECK_DYNAMIC_PROMPT                 0x0053 // not referenced
//#define STR_CHECK_DYNAMIC_HELP                   0x0054 // not referenced
//#define STR_NUMERIC_PROMPT                       0x0055 // not referenced
//#define STR_NUMERIC_PROMPT1                      0x0056 // not referenced
//#define STR_NUMERIC_HELP3                        0x0057 // not referenced
//#define STR_ERROR_INCONSISTENT                   0x0058 // not referenced
//#define STR_RESTORE_DEFAULTS_PROMPT              0x0059 // not referenced
//#define STR_RESTORE_DEFAULTS_HELP                0x005A // not referenced
//#define STR_SAVE_DEFAULTS_PROMPT                 0x005B // not referenced
//#define STR_SAVE_DEFAULTS_HELP                   0x005C // not referenced
//#define STR_BANNER_TITLE                         0x005D // not referenced
//#define STR_SUPPRESS_IF_TEXT1                    0x005E // not referenced
//#define STR_SUPPRESS_IF_TEXT2                    0x005F // not referenced
//#define STR_GRAYOUT_IF_TEXT1                     0x0060 // not referenced
//#define STR_GRAYOUT_IF_TEXT2                     0x0061 // not referenced
//#define STR_INVENTORY_HELP                       0x0062 // not referenced
//#define STR_INVENTORY_TEXT1                      0x0063 // not referenced
//#define STR_INVENTORY_TEXT2                      0x0064 // not referenced
//#define STR_TEST_STRING                          0x0065 // not referenced
//#define STR_GRAYOUT_TEST                         0x0066 // not referenced
//#define STR_SUPPRESS_TEST                        0x0067 // not referenced
//#define STR_CLEAR_TEST                           0x0068 // not referenced
//#define STR_BOOT_TITLE                           0x0069 // not referenced

#endif
