//
//  DO NOT EDIT -- auto-generated file
//
//  This file is generated by the string gather utility
//
#ifndef _BDSSTRINGS_STRINGS_DEFINE_H_
#define _BDSSTRINGS_STRINGS_DEFINE_H_

// #define $LANGUAGE_NAME                           0x0000
// #define $PRINTABLE_LANGUAGE_NAME                 0x0001
#define STR_FRONT_PAGE_TITLE                     0x0002
#define STR_FRONT_PAGE_COMPUTER_MODEL            0x0003
#define STR_FRONT_PAGE_CPU_MODEL                 0x0004
#define STR_FRONT_PAGE_CPU_SPEED                 0x0005
#define STR_FRONT_PAGE_MEMORY_SIZE               0x0006
#define STR_FRONT_PAGE_BIOS_VERSION              0x0007
#define STR_CONTINUE_PROMPT                      0x0008
#define STR_CONTINUE_HELP                        0x0009
#define STR_LANGUAGE_SELECT                      0x000A
#define STR_LANGUAGE_SELECT_HELP                 0x000B
#define STR_BOOT_MANAGER                         0x000C
#define STR_BOOT_MANAGER_HELP                    0x000D
#define STR_BOOT_MAINT_MANAGER                   0x000E
#define STR_BOOT_MAINT_MANAGER_HELP              0x000F
#define STR_DEVICE_MANAGER                       0x0010
#define STR_DEVICE_MANAGER_HELP                  0x0011
#define STR_NULL_STRING                          0x0012
#define STR_MISSING_STRING                       0x0013
#define STR_BOOT_FAILED                          0x0014
#define STR_BOOT_SUCCEEDED                       0x0015
#define STR_PERFORM_MEM_TEST                     0x0016
#define STR_MEMORY_TEST_PERCENT                  0x0017
#define STR_ESC_TO_SKIP_MEM_TEST                 0x0018
#define STR_MEM_TEST_COMPLETED                   0x0019
#define STR_SYSTEM_MEM_ERROR                     0x001A
#define STR_START_BOOT_OPTION                    0x001B
#define STR_NONE                                 0x001C
#define STR_FORM_MAIN_TITLE                      0x001D
#define STR_FORM_BOOT_SETUP_TITLE                0x001E
#define STR_FORM_BOOT_SETUP_HELP                 0x001F
#define STR_FORM_DRIVER_SETUP_TITLE              0x0020
#define STR_FORM_DRIVER_SETUP_HELP               0x0021
#define STR_FORM_BOOT_ADD_TITLE                  0x0022
#define STR_FORM_BOOT_ADD_HELP                   0x0023
#define STR_FORM_BOOT_DEL_TITLE                  0x0024
#define STR_FORM_NEXT_BOOT_HELP                  0x0025
#define STR_FORM_BOOT_CHG_TITLE                  0x0026
#define STR_FORM_DRV_ADD_TITLE                   0x0027
#define STR_FORM_DRV_ADD_HELP                    0x0028
#define STR_FORM_DRV_DEL_TITLE                   0x0029
#define STR_FORM_DRV_CHG_TITLE                   0x002A
#define STR_FORM_BOOT_NEXT_TITLE                 0x002B
#define STR_FORM_BOOT_NEXT_HELP                  0x002C
#define STR_FORM_TIME_OUT_TITLE                  0x002D
#define STR_FORM_TIME_OUT_HELP                   0x002E
#define STR_FORM_CON_MAIN_TITLE                  0x002F
#define STR_FORM_CON_MAIN_HELP                   0x0030
#define STR_FORM_CON_IN_TITLE                    0x0031
#define STR_FORM_CON_IN_HELP                     0x0032
#define STR_FORM_SET_FD_ORDER_TITLE              0x0033
#define STR_FORM_SET_HD_ORDER_TITLE              0x0034
#define STR_FORM_SET_CD_ORDER_TITLE              0x0035
#define STR_FORM_SET_NET_ORDER_TITLE             0x0036
#define STR_FORM_SET_BEV_ORDER_TITLE             0x0037
#define STR_FORM_CON_OUT_TITLE                   0x0038
#define STR_FORM_CON_OUT_HELP                    0x0039
#define STR_FORM_STD_ERR_TITLE                   0x003A
#define STR_FORM_STD_ERR_HELP                    0x003B
#define STR_FORM_MODE_TITLE                      0x003C
#define STR_FORM_MODE_HELP                       0x003D
#define STR_FORM_COM_TITLE                       0x003E
#define STR_FORM_COM_HELP                        0x003F
#define STR_FORM_DRV_ADD_FILE_TITLE              0x0040
#define STR_FORM_DRV_ADD_HANDLE_TITLE            0x0041
#define STR_FORM_BOOT_ADD_DESC_TITLE             0x0042
#define STR_FORM_DRV_ADD_DESC_TITLE              0x0043
#define STR_NUM_AUTO_BOOT                        0x0044
#define STR_HLP_AUTO_BOOT                        0x0045
#define STR_BOOT_NEXT                            0x0046
#define STR_BOOT_NEXT_HELP                       0x0047
#define STR_LOAD_OPTION_DESC                     0x0048
#define STR_LOAD_OPTION_FORCE_RECON              0x0049
#define STR_SAVE_AND_EXIT                        0x004A
#define STR_NO_SAVE_AND_EXIT                     0x004B
#define STR_CON_MODE_SETUP                       0x004C
#define STR_CON_COM_SETUP                        0x004D
#define STR_COM_TERMI_TYPE                       0x004E
#define STR_COM_BAUD_RATE                        0x004F
#define STR_COM_DATA_BITS                        0x0050
#define STR_COM_PARITY                           0x0051
#define STR_COM_STOP_BITS                        0x0052
#define STR_COM_BAUD_RATE_0                      0x0053
#define STR_COM_BAUD_RATE_1                      0x0054
#define STR_COM_BAUD_RATE_2                      0x0055
#define STR_COM_BAUD_RATE_3                      0x0056
#define STR_COM_BAUD_RATE_4                      0x0057
#define STR_COM_BAUD_RATE_5                      0x0058
#define STR_COM_BAUD_RATE_6                      0x0059
#define STR_COM_BAUD_RATE_7                      0x005A
#define STR_COM_BAUD_RATE_8                      0x005B
#define STR_COM_BAUD_RATE_9                      0x005C
#define STR_COM_BAUD_RATE_10                     0x005D
#define STR_COM_BAUD_RATE_11                     0x005E
#define STR_COM_BAUD_RATE_12                     0x005F
#define STR_COM_BAUD_RATE_13                     0x0060
#define STR_COM_BAUD_RATE_14                     0x0061
#define STR_COM_BAUD_RATE_15                     0x0062
#define STR_COM_BAUD_RATE_16                     0x0063
#define STR_COM_BAUD_RATE_17                     0x0064
#define STR_COM_BAUD_RATE_18                     0x0065
#define STR_COM_DATA_BITS_0                      0x0066
#define STR_COM_DATA_BITS_1                      0x0067
#define STR_COM_DATA_BITS_2                      0x0068
#define STR_COM_DATA_BITS_3                      0x0069
#define STR_COM_PAR_0                            0x006A
#define STR_COM_PAR_1                            0x006B
#define STR_COM_PAR_2                            0x006C
#define STR_COM_PAR_3                            0x006D
#define STR_COM_PAR_4                            0x006E
#define STR_COM_STOP_BITS_0                      0x006F
#define STR_COM_STOP_BITS_1                      0x0070
#define STR_COM_STOP_BITS_2                      0x0071
#define STR_COM_TYPE_0                           0x0072
#define STR_COM_TYPE_1                           0x0073
#define STR_COM_TYPE_2                           0x0074
#define STR_COM_TYPE_3                           0x0075
#define STR_RESET                                0x0076
#define STR_FORM_GOTO_MAIN                       0x0077
#define STR_BOOT_FROM_FILE                       0x0078
#define STR_BOOT_FROM_FILE_HELP                  0x0079
#define STR_OPTIONAL_DATA                        0x007A
#define STR_CHANGE_ORDER                         0x007B
#define STR_DISABLE_LEGACY_DEVICE                0x007C
#define STR_FILE_EXPLORER_TITLE                  0x007D
#define STR_BM_BANNER                            0x007E
#define STR_HELP_FOOTER                          0x007F
#define STR_BOOT_OPTION_BANNER                   0x0080
#define STR_ANY_KEY_CONTINUE                     0x0081
#define STR_LAST_STRING                          0x0082
#define STR_DEVICE_MANAGER_TITLE                 0x0083
#define STR_DISK_DEVICE                          0x0084
#define STR_VIDEO_DEVICE                         0x0085
#define STR_NETWORK_DEVICE                       0x0086
#define STR_INPUT_DEVICE                         0x0087
#define STR_ON_BOARD_DEVICE                      0x0088
#define STR_OTHER_DEVICE                         0x0089
#define STR_EXIT_STRING                          0x008A
#define STR_ONE_OF_VBIOS                         0x008B
#define STR_ONE_OF_VBIOS_HELP                    0x008C
#define STR_ONE_OF_PCI                           0x008D
#define STR_ONE_OF_AGP                           0x008E
#define STR_EMPTY_STRING                         0x008F
//#define STR_FRONT_PAGE_BANNER_0_LEFT             0x0090 // not referenced
//#define STR_FRONT_PAGE_BANNER_0_RIGHT            0x0091 // not referenced
//#define STR_FRONT_PAGE_BANNER_1_LEFT             0x0092 // not referenced
//#define STR_FRONT_PAGE_BANNER_1_RIGHT            0x0093 // not referenced
//#define STR_FRONT_PAGE_BANNER_2_LEFT             0x0094 // not referenced
//#define STR_FRONT_PAGE_BANNER_3_LEFT             0x0095 // not referenced
//#define STR_TIME_OUT_PROMPT                      0x0096 // not referenced
//#define STR_INTERNAL_EFI_SHELL                   0x0097 // not referenced
//#define STR_LEGACY_BOOT_A                        0x0098 // not referenced
//#define STR_PROCESSED_ALL_BOOT_OPTIONS           0x0099 // not referenced
//#define STR_DEFAULT_TIMEOUT_BANNER               0x009A // not referenced
//#define STR_SECONDS                              0x009B // not referenced
//#define STR_EXIT_DATA                            0x009C // not referenced
//#define STR_LOADING                              0x009D // not referenced
//#define STR_ENTER_NORMAL_BOOT                    0x009E // not referenced
//#define STR_NO_EXT_MEM_FOUND                     0x009F // not referenced
//#define STR_FORM_GOTO_SETTING                    0x00A0 // not referenced
//#define STR_COM1                                 0x00A1 // not referenced
//#define STR_COM2                                 0x00A2 // not referenced
//#define STR_COM_AS_CONSOLE_OPTION                0x00A3 // not referenced
//#define STR_LOAD_OPTION_DEVPATH                  0x00A4 // not referenced
//#define STR_LOAD_OPTION_ACTIVE                   0x00A5 // not referenced
//#define STR_CON_IN_SETUP                         0x00A6 // not referenced
//#define STR_CON_OUT_SETUP                        0x00A7 // not referenced
//#define STR_CON_ERR_SETUP                        0x00A8 // not referenced
//#define STR_BOOT_LEGACY                          0x00A9 // not referenced
//#define STR_BOOT_LEGACY_HELP                     0x00AA // not referenced
//#define STR_BOOT_LEGACY_FLOPPY                   0x00AB // not referenced
//#define STR_BOOT_LEGACY_HARDDRIVE                0x00AC // not referenced
//#define STR_BOOT_LEGACY_CDROM                    0x00AD // not referenced
//#define STR_BOOT_LEGACY_PCMCIA                   0x00AE // not referenced
//#define STR_BOOT_LEGACY_USB                      0x00AF // not referenced
//#define STR_BOOT_LEGACY_NETWORK                  0x00B0 // not referenced
//#define STR_AND                                  0x00B1 // not referenced

#endif
